### ISSUE TITLE
支付设定

### ISSUE THREAD

**Issue by EthanYa** [kaelzhang/egg-wechat-pay#1]
请问支付方式如何设定?

**Comment by kaelzhang** [comment]
请问你的问题是什么意思

**Comment by EthanYa** [comment]
支付模式有四种 (trade_type)
1、刷卡支付 (MICROPAY)
2、扫码支付 (NATIVE)
3、公众号支付 (JSAPI)
4、APP支付 (APP)
我疑惑点，是因为看了一下源码支付模式预设JSAPI
包装 wechat-pay 所应该在 统一下单(await wechatPay.requestPayment(order))设定支付设定就好，文档刚好没写到所以觉得有点疑惑。
